FROM --platform=linux/amd64 ubuntu@sha256:86ac87f73641c920fb42cc9612d4fb57b5626b56ea2a19b894d0673fd5b4f2e9 AS build

RUN apt-get update -y && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY provided.c .

RUN gcc -o compiled provided.c
